// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsBlazorApp.Models;

#nullable disable

namespace StudentsBlazorApp.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220613061517_updatestudentmodel2")]
    partial class updatestudentmodel2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("StudentsBlazorApp.Models.classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("class_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("StudentsBlazorApp.Models.countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("StudentsBlazorApp.Models.students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("TEXT");

                    b.Property<int>("student_classId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("student_countryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("student_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("student_classId");

                    b.HasIndex("student_countryId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("StudentsBlazorApp.Models.students", b =>
                {
                    b.HasOne("StudentsBlazorApp.Models.classes", "student_class")
                        .WithMany("students")
                        .HasForeignKey("student_classId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentsBlazorApp.Models.countries", "student_country")
                        .WithMany("students")
                        .HasForeignKey("student_countryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student_class");

                    b.Navigation("student_country");
                });

            modelBuilder.Entity("StudentsBlazorApp.Models.classes", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("StudentsBlazorApp.Models.countries", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
